data <- read.csv("Dataset3final.csv", stringsAsFactors = TRUE)
mean(data$Women.Entrepreneurship.Index)
median(data$Women.Entrepreneurship.Index)
sd(data$Women.Entrepreneurship.Index)
mean(data$Entrepreneurship.Index)
sd(data$Entrepreneurship.Index)
mean(data$Female.Labor.Force.Participation.Rate)
sd(data$Female.Labor.Force.Participation.Rate)
table(data$European.Union.Membership)
table(data$Level.of.development)
